#!/bin/sh

exec 3<&0

$PERL -x <<'END_OF_SCRIPT'
#!perl

use CGI::ExtDirect;

use RPC::ExtDirect::API     Namespace       => 'myApp.ns',
                            Router_path     => '/router.cgi',
                            Poll_path       => '/poll.cgi',
                            Remoting_var    => 'Ext.app.REMOTE_CALL',
                            Polling_var     => 'Ext.app.REMOTE_POLL',
                            Auto_Connect    => 1;

use RPC::ExtDirect::Test::Pkg::Foo;
use RPC::ExtDirect::Test::Pkg::Bar;
use RPC::ExtDirect::Test::Pkg::Qux;

open STDIN, '<&=', 3 or die "Can't reopen STDIN";

my $cgi = CGI::ExtDirect->new({ debug => 1 });

print $cgi->api();

exit 0;
