#!/bin/sh

exec 3<&0

$PERL -x <<'END_OF_SCRIPT'
#!perl

use CGI::ExtDirect;

use RPC::ExtDirect::API     Namespace       => 'Namespace',
                            Router_path     => '/cgi-bin/router.cgi',
                            Poll_path       => '/cgi-bin/events.cgi',
                            Remoting_var    => 'Ext.app.CALL',
                            Polling_var     => 'Ext.app.POLL',
                        ;

use RPC::ExtDirect::Test::Pkg::Foo;
use RPC::ExtDirect::Test::Pkg::Bar;
use RPC::ExtDirect::Test::Pkg::Qux;
use RPC::ExtDirect::Test::Pkg::PollProvider;

open STDIN, '<&3' or die "Can't reopen STDIN";

my $cgi = CGI::ExtDirect->new({ debug => 1 });

print $cgi->api();

exit 0;
