#!/bin/sh

exec 3<&0

$PERL -x <<'END_OF_SCRIPT'
#!perl

use CGI::ExtDirect;

use RPC::ExtDirect::Test::Pkg::PollProvider;

open STDIN, '<&3' or die "Can't reopen STDIN";

local $RPC::ExtDirect::Test::Pkg::PollProvider::WHAT_YOURE_HAVING = '';

my $cgi = CGI::ExtDirect->new({ debug => 1 });

my %headers = (
    '-Status'           => '204 No Response',
    '-Content-type'     => 'text/plain',
    '-ChArSeT'          => 'iso-8859-1',
    '-Content_Length'   => '123123',
);

print $cgi->poll( %headers );

exit 0;

END_OF_SCRIPT

