#!/bin/sh

exec 3<&0

$PERL -x <<'END_OF_SCRIPT'
#!perl

use CGI::ExtDirect;

use RPC::ExtDirect::Test::Pkg::Foo;
use RPC::ExtDirect::Test::Pkg::JuiceBar;
use RPC::ExtDirect::Test::Pkg::Qux;

open STDIN, '<&=', 3 or die "Can't reopen STDIN";

my $debug   = 1;
my %headers = ();

my $cgi = CGI::ExtDirect->new({ debug => 1 });

print $cgi->route(%headers);

exit 0;
